/*
 * This file is generated by jOOQ.
 */
package br.eti.sca.customersapi.model.jooq.tables.records;


import br.eti.sca.customersapi.model.jooq.tables.TbCustomer;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbCustomerRecord extends UpdatableRecordImpl<TbCustomerRecord> implements Record7<Integer, Long, String, String, String, Date, String> {

    private static final long serialVersionUID = 1250262300;

    /**
     * Setter for <code>db_company.tb_customer.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_company.tb_customer.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_company.tb_customer.nr_register</code>.
     */
    public void setNrRegister(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_company.tb_customer.nr_register</code>.
     */
    public Long getNrRegister() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>db_company.tb_customer.ds_usename</code>.
     */
    public void setDsUsename(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_company.tb_customer.ds_usename</code>.
     */
    public String getDsUsename() {
        return (String) get(2);
    }

    /**
     * Setter for <code>db_company.tb_customer.ds_password</code>.
     */
    public void setDsPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_company.tb_customer.ds_password</code>.
     */
    public String getDsPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>db_company.tb_customer.ds_name</code>.
     */
    public void setDsName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_company.tb_customer.ds_name</code>.
     */
    public String getDsName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>db_company.tb_customer.dt_birth</code>.
     */
    public void setDtBirth(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>db_company.tb_customer.dt_birth</code>.
     */
    public Date getDtBirth() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>db_company.tb_customer.ds_email</code>.
     */
    public void setDsEmail(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>db_company.tb_customer.ds_email</code>.
     */
    public String getDsEmail() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Long, String, String, String, Date, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Long, String, String, String, Date, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TbCustomer.TB_CUSTOMER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return TbCustomer.TB_CUSTOMER.NR_REGISTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TbCustomer.TB_CUSTOMER.DS_USENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TbCustomer.TB_CUSTOMER.DS_PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TbCustomer.TB_CUSTOMER.DS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return TbCustomer.TB_CUSTOMER.DT_BIRTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return TbCustomer.TB_CUSTOMER.DS_EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getNrRegister();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDsUsename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDsPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component6() {
        return getDtBirth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDsEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getNrRegister();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDsUsename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDsPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDsName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getDtBirth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDsEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCustomerRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCustomerRecord value2(Long value) {
        setNrRegister(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCustomerRecord value3(String value) {
        setDsUsename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCustomerRecord value4(String value) {
        setDsPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCustomerRecord value5(String value) {
        setDsName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCustomerRecord value6(Date value) {
        setDtBirth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCustomerRecord value7(String value) {
        setDsEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbCustomerRecord values(Integer value1, Long value2, String value3, String value4, String value5, Date value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbCustomerRecord
     */
    public TbCustomerRecord() {
        super(TbCustomer.TB_CUSTOMER);
    }

    /**
     * Create a detached, initialised TbCustomerRecord
     */
    public TbCustomerRecord(Integer id, Long nrRegister, String dsUsename, String dsPassword, String dsName, Date dtBirth, String dsEmail) {
        super(TbCustomer.TB_CUSTOMER);

        set(0, id);
        set(1, nrRegister);
        set(2, dsUsename);
        set(3, dsPassword);
        set(4, dsName);
        set(5, dtBirth);
        set(6, dsEmail);
    }
}
