/*
 * This file is generated by jOOQ.
 */
package br.eti.sca.customersapi.model.jooq;


import br.eti.sca.customersapi.model.jooq.tables.TbCustomer;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>db_company</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index TB_CUSTOMER_DS_USENAME = Indexes0.TB_CUSTOMER_DS_USENAME;
    public static final Index TB_CUSTOMER_NR_NUMBER = Indexes0.TB_CUSTOMER_NR_NUMBER;
    public static final Index TB_CUSTOMER_PRIMARY = Indexes0.TB_CUSTOMER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index TB_CUSTOMER_DS_USENAME = Internal.createIndex("ds_usename", TbCustomer.TB_CUSTOMER, new OrderField[] { TbCustomer.TB_CUSTOMER.DS_USENAME }, true);
        public static Index TB_CUSTOMER_NR_NUMBER = Internal.createIndex("nr_number", TbCustomer.TB_CUSTOMER, new OrderField[] { TbCustomer.TB_CUSTOMER.NR_REGISTER }, true);
        public static Index TB_CUSTOMER_PRIMARY = Internal.createIndex("PRIMARY", TbCustomer.TB_CUSTOMER, new OrderField[] { TbCustomer.TB_CUSTOMER.ID }, true);
    }
}
