/*
 * This file is generated by jOOQ.
 */
package br.eti.sca.customersapi.model.jooq;


import br.eti.sca.customersapi.model.jooq.tables.TbCustomer;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in db_company
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>db_company.tb_customer</code>.
     */
    public static final TbCustomer TB_CUSTOMER = br.eti.sca.customersapi.model.jooq.tables.TbCustomer.TB_CUSTOMER;
}
